API connection base code and reformat of code
CaedenPH/Jarvide pull request #102
Opened 2022-01-10 16:35 UTC by Nipa-Code

Create API connection with aiohttp, reformat code with black and help of flake8. Create tox.ini for ignoring some flake8 errors/warnings. I placed the most stuff in commit message :/
Saying it again: Code is NOT tested.

2022-01-10 16:56 UTC, sifte approved these changes

2022-01-10 17:07 UTC, Yat-o commented
so what you're trying to say is you made this big ass pr without testing any of the code….

2022-01-10 17:22 UTC, Pandabweer commented on src/bot.py
> +            allowed_mentions=AllowedMentions(everyone=False, roles=False),
Unnecessary extra comma.

2022-01-10 17:23 UTC, Pandabweer commented on src/bot.py
> +import aiohttp
For continuation and consistency import are placed a the top, from import below.

2022-01-10 17:27 UTC, Pandabweer commented on src/cogs/config.py
> +    has_permissions,
Unnecessary extra comma again.

2022-01-10 17:28 UTC, Pandabweer commented on src/cogs/errors.py
> +                    color=Color.red(),
Unnecessary extra comma again.

2022-01-10 17:29 UTC, Pandabweer commented on src/cogs/config.py
> +            "createconf",
Unnecessary extra comma again.

2022-01-10 17:29 UTC, Pandabweer commented on src/cogs/config.py
>          manage_guild=True,
Unnecessary extra comma again (i know some aren't your fault).

2022-01-10 17:30 UTC, Pandabweer commented on src/cogs/help.py
> +                "ide",
Unnecessary extra comma again.

2022-01-10 17:31 UTC, Pandabweer commented on src/cogs/help.py
>          command_help_dict = {
This is also not your fault but when having a lot of 'or' operators please use the `any()` function that Python has.

2022-01-10 17:32 UTC, Pandabweer commented on src/cogs/help.py
> +                "errorhandler",
Unnecessary extra comma again.

2022-01-10 17:32 UTC, Pandabweer commented on src/cogs/help.py
> +                ephemeral=True,
Unnecessary extra comma again.

2022-01-10 17:32 UTC, Pandabweer commented on src/cogs/ide/auto_detect.py
> +    "abs": lambda x: math.fabs(x),
Unnecessary extra comma again.

2022-01-10 17:34 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            "Successfully restored version!", ephemeral=True
Try to stay consistent, at other files you placed ephemeral on a separate line and now you kept it here.

2022-01-10 17:34 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            disnake.SelectOption(value="3", label="Version History"),
Unnecessary extra comma again.

2022-01-10 17:34 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            ephemeral=True,
Unnecessary extra comma again.

2022-01-10 17:34 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +                and m.channel == interaction.channel,
Unnecessary extra comma again.

2022-01-10 17:35 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +                timeout=60,
Unnecessary extra comma again.

2022-01-10 17:35 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            and m.channel == interaction.channel,
Unnecessary extra comma again.

2022-01-10 17:37 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +        return ["".join(lines[x : x + 50]) for x in range(0, len(lines), 50)]
PEP8 states index or dict key-value assignments should be `[x: x + 50]` this should be reversed.

2022-01-10 17:37 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +                and m.channel == interaction.channel,
Unnecessary extra comma again.

2022-01-10 17:37 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +        del sliced[from_ : to + 1]
Again this should be `sliced[from_: to + 1]`

2022-01-10 17:38 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +                    and m.channel == interaction.channel,
Unnecessary extra comma again.

2022-01-10 17:38 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            ephemeral=True,
Unnecessary extra comma again.

2022-01-10 17:38 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            and m.channel == interaction.channel,
Unnecessary extra comma again.

2022-01-10 17:38 UTC, Pandabweer commented on src/cogs/ide/dialogs/edit_view.py
> +            and m.channel == self.ctx.channel,
Unnecessary extra comma again.

2022-01-10 17:38 UTC, Pandabweer commented on src/cogs/ide/dialogs/file_view.py
> +                json={"language": name, "source": content},
Unnecessary extra comma again.

2022-01-10 17:39 UTC, Pandabweer commented on src/cogs/ide/dialogs/file_view.py
> +                f"\n1/{math.ceil(len(content) / 50)}",
Unnecessary extra comma again.

2022-01-10 17:39 UTC, Pandabweer commented on src/cogs/ide/dialogs/file_view.py
> +            and m.channel == self.ctx.channel,
Unnecessary extra comma again.

2022-01-10 17:39 UTC, Pandabweer commented on src/cogs/ide/dialogs/file_view.py
> +                and m.channel == self.ctx.channel,
Unnecessary extra comma again.

2022-01-10 17:39 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +                and not self.is_exited,
Unnecessary extra comma again.

2022-01-10 17:39 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +                and not self.is_exited,
Unnecessary extra comma again.

2022-01-10 17:40 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +                        delete_after=5,
Unnecessary extra comma again.

2022-01-10 17:40 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            content = "\n".join(content.splitlines()[int(start) - 1 : int(end)])
Line should be:
`content = "\n".join(content.splitlines()[int(start) - 1: int(end)])`

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +                and not self.is_exited,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            and not self.is_exited,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            and not self.is_exited,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            "Open a file from saved:\nCurrent directory: /",
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            start=1,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +                    ephemeral=True,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            timestamp=interaction.message.created_at,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/dialogs/open_view.py
> +            icon_url=interaction.author.avatar.url,
Unnecessary extra comma again.

2022-01-10 17:41 UTC, Pandabweer commented on src/cogs/ide/ide.py
> +        aliases=["texteditor", "editor"],
Unnecessary extra comma again.

2022-01-10 17:42 UTC, Pandabweer commented on src/cogs/misc.py
> +                "explain your report. present as detailed of a description as you can provide, including button clicks, errors shown (if any), file open, and intention",
This line is still way too long, thanks for shortening it just a bit.

2022-01-10 17:43 UTC, Pandabweer commented on src/cogs/misc.py
> +            timestamp=ctx.message.created_at,
Unnecessary extra comma again.

2022-01-10 17:43 UTC, Pandabweer commented on src/utils/paginator.py
> +                text = text[self.breakpoint :]
: is smashed against it. Reverse.

2022-01-10 17:44 UTC, Pandabweer commented on src/cogs/mod.py
> +        reason="No Reason Provided.",
Unnecessary extra comma again.

2022-01-10 17:44 UTC, Pandabweer commented on src/cogs/mod.py
> +        slowmode: int = None,
Unnecessary extra comma again.

2022-01-10 17:44 UTC, Pandabweer commented on src/cogs/mod.py
> +        slowmode: int = None,
Unnecessary extra comma again.

2022-01-10 17:44 UTC, Pandabweer commented on src/cogs/mod.py
> +        reason="No Reason Provided.",
Unnecessary extra comma again.

2022-01-10 17:44 UTC, Pandabweer commented on src/cogs/mod.py
> +        reason: str = "No Reason Provided.",
Unnecessary extra comma again.

2022-01-10 17:46 UTC, Pandabweer requested changes
Consistency is a bit wonky and there are some small fixes but overall great cleanup of single quotes, unnecessary f-strings and a lot of long code shortened.

2022-01-11 00:00 UTC, NotFlameDev commented on src/cogs/help.py
>          command_help_dict = {
That's not a conditional statement, so you can't use `any()` there

2022-01-11 00:56 UTC, NotFlameDev reviewed
Removing everything in `__init__.py` raises a bunch of `ImportError`

2022-01-11 05:12 UTC, Nipa-Code commented
@NotFlameDev they were unused imports tho

2022-01-11 07:02 UTC, NotFlameDev commented
> @NotFlameDev they were unused imports tho

they are unused in `__init__.py` but it's used in other files. And without them, you can't import the stuff

2022-01-11 11:39 UTC, NotFlameDev approved these changes

2022-01-11 16:26 UTC, Pandabweer commented on src/bot.py
> +        self.session = None
Define a session

2022-01-11 16:48 UTC, Pandabweer approved these changes

2022-01-11 16:48 UTC, merged