Fixed stuff
CaedenPH/Jarvide pull request #104
Opened 2022-01-11 03:13 UTC by NotFlameDev

- Fixed detect_calc got triggered on single negative number. E.g. `-1` or `--3`

2022-01-11 16:31 UTC, Pandabweer requested changes
github.py needs to get changed or deleted.

2022-01-11 16:31 UTC, Pandabweer commented on src/cogs/ide/github.py
> +            "Authorization": ...  # TODO: Get token from database
I don't like TODO comments inside code, please just finish the code, if you need something else, like a .env or config file please make that first.

2022-01-11 16:31 UTC, Pandabweer commented on src/cogs/ide/github.py
> +    async with aiohttp.ClientSession() as session:
Bot is getting http_session, please use that when [pull 102](https://github.com/CaedenPH/Jarvide/pull/102) is finished.

2022-01-12 00:02 UTC, NotFlameDev commented on src/cogs/ide/github.py
> +            "Authorization": ...  # TODO: Get token from database
the token endpoint isn't ready yet, thus it's a TODO

2022-01-12 17:29 UTC, Pandabweer approved these changes

2022-01-13 00:05 UTC, NotFlameDev commented
> whats this github.py?

GitHub simple API wrapper (not really a wrapper). The place to make requests to GitHub

2022-01-14 15:09 UTC, CaedenPH commented
> > whats this github.py?
> 
> GitHub simple API wrapper (not really a wrapper). The place to make requests to GitHub

why do we need requests to github?

2022-01-15 02:12 UTC, merged