added a new command
CaedenPH/Jarvide pull request #109
Opened 2022-01-14 21:13 UTC by Dhruvin12

2022-01-14 21:14 UTC, Dekriel commented
my first thought is that it looks a bit messy.

2022-01-14 21:15 UTC, Dhruvin12 commented
🤡 maybe you can do some changes

2022-01-14 21:16 UTC, Dekriel commented
ok

2022-01-15 02:11 UTC, sifte requested changes
emoji's wont work

2022-01-15 02:14 UTC, sifte approved these changes

2022-01-15 05:54 UTC, sarthak-py requested changes

2022-01-15 05:54 UTC, sarthak-py commented on src/cogs/mod.py
> +        embed.set_thumbnail(url=member.avatar_url)
outdated `avatar_url`

2022-01-15 05:54 UTC, sarthak-py commented on src/cogs/mod.py
> +        embed.set_thumbnail(url=member.avatar_url)
you might like using `display_avatar` mb

2022-01-15 15:35 UTC, sarthak-py approved these changes

2022-01-16 18:07 UTC, closed without merging