Made a giveaway command
CaedenPH/Jarvide pull request #124
Opened 2022-01-22 23:33 UTC by RopraMMC

(: even caeden likes it so it is good (although he bullied me)

2022-01-22 23:34 UTC, Dekriel commented
what happens in discord stays in discord.

2022-01-22 23:41 UTC, RopraMMC commented
note: intents but be all

2022-01-23 03:45 UTC, Yat-o commented
Dude wtf did you seriously add asyncio to the requirements file

2022-01-23 03:49 UTC, Yat-o requested changes

2022-01-23 03:49 UTC, Yat-o commented on src/cogs/misc.py
> +    winnerList = []
camel case is not pep8 compliant

2022-01-23 03:49 UTC, Yat-o commented on src/cogs/misc.py
> +    await asyncio.sleep(giveawayTime)
sleeping is a bad way to handle giveaways. What if the bot goes offline. The state of the sleep isn’t saved.

2022-01-23 03:49 UTC, Yat-o commented
There’s some more stuff but you know. You’ll get those.

2022-01-23 03:53 UTC, realstealthninja commented on src/cogs/misc.py
> +    await asyncio.sleep(giveawayTime)
i have to agree with yat-o here alot of ways this could fail

2022-01-23 03:53 UTC, Yat-o commented on src/cogs/misc.py
> +    users.pop(users.index(self.bot.user))
You don’t even need to do this. Just use list comprehension when you make the initial list. 

```py
[user for user in message.reactions[0].users().flatten() if not user.bot]
```
Something along those lines

2022-01-23 03:54 UTC, realstealthninja requested changes
needs a way to save time

2022-01-23 11:54 UTC, RopraMMC commented on src/cogs/misc.py
> +    winnerList = []
HSIT I FORGT TO CHANGE THEM
SHIT

2022-01-26 10:48 UTC, RopraSchool commented
Yo imm gonna close this when I get home, I am going to start edititing from school aswell

2022-01-26 10:50 UTC, RopraSchool commented on src/cogs/misc.py
> +    await asyncio.sleep(giveawayTime)
I can't be asked to fix it so im going to just going to close when im home

2022-01-26 11:48 UTC, closed without merging