New `setnick` command
CaedenPH/Jarvide pull request #126
Opened 2022-01-27 12:12 UTC by DTS-11

Changes nickname of a user in the server.

2022-01-27 13:03 UTC, sifte requested changes
there a conflicts that need to be resolved

2022-01-27 14:25 UTC, Yat-o commented
Did you not pull or something before you did this?

2022-01-28 05:22 UTC, sarthak-py requested changes

2022-01-28 05:22 UTC, sarthak-py commented on src/cogs/mod.py
> +        await ctx.send(f'Nickname for {member.name} was changed to {member.mention}')
misses hierarchy check, no handling if the bot is unable to edit the nickname of the member ,

2022-01-28 07:17 UTC, DTS-11 commented on src/cogs/mod.py
> +        await ctx.send(f'Nickname for {member.name} was changed to {member.mention}')
we can make error handling for that in another cog...

2022-01-28 09:04 UTC, sarthak-py commented on src/cogs/mod.py
> +        await ctx.send(f'Nickname for {member.name} was changed to {member.mention}')
i dont see how the error handler will handle a hierarchy check and discord.Forbidden Error for a single command

2022-01-28 11:56 UTC, DTS-11 commented on src/cogs/mod.py
> +        await ctx.send(f'Nickname for {member.name} was changed to {member.mention}')
I will make another PR. closing this now

2022-01-28 19:34 UTC, DTS-11 commented
I'll make another PR... idk much of github.. (this is so complicated :/)

2022-01-28 19:34 UTC, closed without merging