duration for `ban` command
CaedenPH/Jarvide pull request #130
Opened 2022-02-05 11:15 UTC by osam7a

2022-02-05 16:53 UTC, sifte approved these changes

2022-02-15 07:19 UTC, realstealthninja commented on src/cogs/mod.py
> +            dur = disnake.utils.utcnow() + time_str.convert(duration)
should really add a try execpt around it if the duration doesnt get converted.

2022-02-15 07:20 UTC, realstealthninja requested changes

2022-02-15 07:20 UTC, realstealthninja commented on src/cogs/mod.py
> +        else:
should really add a try execpt over here to see if the duration actually gets converted

2022-10-15 13:01 UTC, closed without merging