new `setnick` command with hierarchy check.
CaedenPH/Jarvide pull request #134
Opened 2022-02-15 14:14 UTC by DTS-11

2022-02-16 05:23 UTC, realstealthninja approved these changes
everything looks fine.
few notes:
 - it would have been nice if it was an embed
 - making it delete after a certain time would also be a good addition
other than this everything is good! 👍

2022-02-16 11:18 UTC, DTS-11 commented
> everything looks fine. few notes:
> 
> * it would have been nice if it was an embed
> * making it delete after a certain time would also be a good addition
>   other than this everything is good! 👍

does other commands delete on its own?

2022-02-16 11:30 UTC, realstealthninja commented
why i mean by deleting is adding `delete_after=10`
```py
await ctx.send(f'Nickname for {member.name} was changed to {member.mention}', delete_after=10)
```

2022-02-16 12:19 UTC, DTS-11 commented
> why i mean by deleting is adding `delete_after=10`
> 
> ```python
> await ctx.send(f'Nickname for {member.name} was changed to {member.mention}', delete_after=10)
> ```

for now, no need of embed.. anyway its gonna delete its msg

2022-02-16 12:31 UTC, realstealthninja commented
very good!

2022-02-16 12:31 UTC, realstealthninja approved these changes

2022-02-16 14:08 UTC, Yat-o requested changes
It was also be imperative to check how the length of how land characters `nick` is. If you try to change someone’s name to something over 36(I think) characters. It will throw an HTTPException.

2022-02-16 14:08 UTC, Yat-o commented on src/cogs/mod.py
> +            return await ctx.send("You cant change someone's nickname that is higher or the same role heirarchy.")
This doesn’t seem like a right error message to put out. The logical check you added only passes if they are only greater than the commands author. Not if they are greater or equal to.

2022-02-16 14:08 UTC, Yat-o commented on src/cogs/mod.py
> +        await member.edit(nick=nick)
Inconsistent use of quotes. Black your code.

2022-02-16 14:08 UTC, Yat-o commented on src/cogs/mod.py
> +    async def setnick(self, ctx, member: disnake.Member, *, nick):
Type hint `ctx` to `commands.Context`

2022-02-16 14:34 UTC, DTS-11 commented on src/cogs/mod.py
> +        await member.edit(nick=nick)
wdym?

2022-02-16 15:39 UTC, Yat-o commented on src/cogs/mod.py
> +        await member.edit(nick=nick)
You're using single quotes where you should be using double quotes for consistency.

2022-02-16 18:54 UTC, DTS-11 commented on src/cogs/mod.py
> +        await member.edit(nick=nick)
> You're using single quotes where you should be using double quotes for consistency.

which line?

2022-02-16 22:14 UTC, Yat-o commented on src/cogs/mod.py
> +        await member.edit(nick=nick)
62

2022-03-04 09:38 UTC, DTS-11 commented
> It was also be imperative to check how the length of how land characters `nick` is. If you try to change someone’s name to something over 36(I think) characters. It will throw an HTTPException.

done..

2022-03-04 12:24 UTC, Yat-o requested changes

2022-03-04 12:24 UTC, Yat-o commented on src/cogs/mod.py
> +            return await ctx.send("You cant change someone's nickname that is higher or the same role heirarchy.")
This still hasn’t been resolved for conciseness

2022-03-04 13:08 UTC, Kirk-KD commented on src/cogs/mod.py
> +            return await ctx.send("You cant change someone's nickname that is higher or the same role heirarchy.")
It is correct, it says if the sender's top role is NOT greater than the other user, which means smaller or equal to.

2022-03-04 14:02 UTC, Yat-o commented on src/cogs/mod.py
> +            return await ctx.send("You cant change someone's nickname that is higher or the same role heirarchy.")
Look at the logical check again. It only checks for greater than.

2022-03-04 14:04 UTC, Yat-o commented on src/cogs/mod.py
> +            return await ctx.send("You cant change someone's nickname that is higher or the same role heirarchy.")
Oh yeah. I just now saw the `not`

2022-03-04 14:05 UTC, Yat-o approved these changes

2022-03-06 17:51 UTC, merged