update slap
CaedenPH/Jarvide pull request #64
Opened 2022-01-05 17:22 UTC by Dekriel

2022-01-05 17:28 UTC, Yat-o requested changes
session isn’t a attribute of our current bot class. And target isn’t a valid name in the command. Revise and commit again.

2022-01-05 18:30 UTC, Robin5605 commented on src/cogs/fun.py
> +                embed=discord.Embed(
Should be `disnake.Embed(...)` to maintain consistency

2022-01-05 18:31 UTC, Robin5605 commented on src/cogs/fun.py
> +        async with self.bot.session.get(
The bot instance doesn't have a session variable like @Yat-o pointed out, though we are working on reusing the `aiohttp.ClientSession()` instance.

2022-01-05 18:32 UTC, Robin5605 requested changes
Please resolve the following issues I have outlined in the comments.

2022-01-09 18:22 UTC, Pandabweer commented
Denied PR because of lack of attention, i suggest finishing on PR before opening a new one.

2022-01-09 18:22 UTC, closed without merging